<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>a night out</h2>
    <p>2026-08</p>
    <p>warning: this is an nsfw story i wrote for a contest (didn't win). it's unlisted so if you're here i likely gave you a direct link. it also doesn't follow my usual <a href=<?= page_url('opinions/style_guide')?> >style guide</a>. read at your own risk.</p>
</div>
<div class="paragraph">
    <p>Kat had just finished her latest project when she heard the apartment front door slam shut, and the sound of a heavy bag hitting the floor. Then an exasperated grunt from her girlfriend as she came into the living room, and slumped down next to her on the couch.</p>

    <p>"Kaaaaat, Im home~" she said in a tired but happy voice, after a long week of dealing with clients at work she finally gets to enjoy some company that knows there isn't a "Capital 5" on a keyboard.</p>

    <p>"Heeyyy Alice, how was work?" she replied.</p>

    <p>"Ehh, same old same old, it seems like people are getting worse and worse with technology. It's like we're actively regressing as people" She snuggled up to Kat as a touch starved puppy and glanced at her work. Her eyes perked up.</p>

    <p>"Is that the new skinsuit?" she asked.</p>

    <p>Kat grinned "It is! Just finished actually, it should be ready for our date tonight."</p>

    <p>If there's one thing that improved Alice's mood more than Kat's soft voice, it was a nice date out in a restaurant. She liked fancy places but not too fancy, places where you could go to a dress but didn't have to. And just as luck would have it, a new place opened up in the town with a nice Italian theme.</p>

    <p>"She looks lovely, where did you get the scans?" She asked. Unlike the general population, Kat was very tech savvy, and managed to get a hold of some yet unreleased technology. Technically stolen, but its better to use it for kinky play than espionage.</p>

    <p>"Well, the legs I got from a really tall athlete I saw on the track on Tuesday, torso I took from another suit... The head is very special, I had a really nice talk with this girl yesterday at her photo shoot, she was cosplaying a character, Mary i think? you'll see why i like it so much"</p>
</div>
<div class="paragraph">
    <p>Alice took the suit and looked at it closely. The suit was slightly taller than her, with very slender legs. The skin tone didn't match the equally slender belly and arms, but the transition between them was well hidden, Kat's been improving with her bonding technique. She was a bit disappointed with the head, its face was of a quite cute woman but it didn't seem to live up to the hype. Short ginger hair, some freckles, a larger but cute nose. Buuut as long as her dear likes it that's more than enough.</p>

    <p>"Go get dressed!" spoke up Kat "We'll be leaving in an hour".</p>

    <p>"Isn't that a little early?"</p>

    <p>"Mmm, maybe, but you'll need to get used to the suit first"</p>

    <p>Alice raised her eyebrow slightly but agreed. She picked up the suit and walked into the bedroom to change. Already on the bed there was a matching asymmetric orange dress and shoes, with the same color as her to-be hair. She sat on the bed and took her sweaty work clothing off and threw it onto the ever-growing laundry pile.</p>

    <p>Sat on the bed, Alice started slipping her legs into the suit. As usual, it had a slightly sticky layer, that resisted at first, but with enough force pulled away and let her slip all the way down without much resistance. The smaller feet posed no problem thanks to some wonderful compression technique that she didn't understand and didn't bother learning. The torso came easily, there was some padding to make her chest fit inside properly, despite that the touch felt very real. As Alice slipped in her right hand Kat came into the room to check.</p>

    <p>"Oh perfect you're almost done" Kat said, then moved closer and sat on the bed behind Alice. "Let me just help you with that" And grabbed the edges of the skinsuit's head.</p>

    <p>"Umm, I guess you can, but I've put on a suit before I know what to do" Alice replied. She went to adjust her face as Kat pulled back on the mask. Neck fit fine, mouth, nose...</p>
</div>
<div class="paragraph">
    <p>Everything went black for her suddenly. More than black, it wasn't as if it got really dark in the room, she couldn't see anything at all, like if she tried to see with her elbow or her mouth. It just wasn't there. She tried to pull the mask off but Kat tugged on it abruptly and pressed the seam together. Alice tried to pull harder but obviously her captor had used an especially quick drying bonder on the mask. This was planned.</p>

    <p>"What's going on?" she asked in a slightly panicked tone. She might not have been able to see it but Kat was very obviously grinning right now.</p>

    <p>"Oh did i forget to tell you? That Mary girl was blind from birth, apparently some developmental issue. The cosplay was gorgeous though, i have no idea how she did it but i was in awe."</p>

    <p>"You have to tell me this in advance, Kat! Do you want me to go out like this?!"</p>

    <p>"I do! And don't tell me you don't want to try it too, i can see your crotch and it doesn't lie."</p>

    <p>Kat was right. Her reasoning was iffy but this sudden situation was very horny, especially with the idea that she'd have to go out into public like this.</p>
</div>
<div class="paragraph">
    <p>If anything, putting the suit on an hour ahead was too optimistic. Alice kept struggling with everything, couldn't properly orient herself in her room. Suddenly the asymmetric dress became a big challenge, and she kept putting her arms and legs into the wrong holes, and had to keep shuffling around. Obviously Kat just stood to the side, giggling the whole time, for all Alice knew she was being recorded on camera for later. After maybe 40 minutes they finally both got dressed.</p>

    <p>"I'm not cruel enough to make you do your makeup" snickered Kat. She grabbed Alice's hand, startling her quite a bit, and pulled her into the bathroom to touch her up a little. Though she had been in this room so many times it now felt so unfamiliar. She was lucky enough to find the sink but the shower and clothes dryer could've been anywhere.</p>

    <p>As Kat worked Alice lightly groped her, exploring her dress and body through her sense of touch and smell. Her dress smelled fresh, with a lavender smell, it had a short drape coming over her chest, and a long skirt that went all the way down to her strong legs. She could tell the dress was beautiful on her, complimenting all her features.</p>

    <p>Suddenly Alice got tugged on again, her handler didn't even bother telling her what she was up to. She heard the sound of the front door open, signalling it was time to go out in public. She could feel her blushing all the way to the taxi, hearing being greeted by neighbours, sheepishly saying her name was Mary when asked. She kept averting her gaze though that obviously didn't do anything.</p>
</div>
<div class="paragraph">
    <p>Alice could hear the murmur of the restaurant as soon as she got lead into the lobby. It sounded like maybe 40 to 50 people.</p>

    <p>"Hello ladies! I'm assuming you're the 9pm reservation?" Asked a pleasant voice, either a greeter or a server.</p>

    <p>"Yes, miss Kat plus one" said Kat's very familiar voice. You could hear her ear-to-ear smile. Alice tried to put on a nice smile but had no idea what she actually looked like, and immediately felt embarrassed again.</p>

    <p>They got seated at a table, and Alice got asked if she wanted a menu in Braille. Trying to keep a bit up with the role-play she agreed, though she had no idea how to read it, or how many dots there even were per character. She tried to at least pretend to read it, gliding her fingers across the lines but she kept slipping between lines and messing up. Someone was definitely staring at her and seeing through her forced lie. God she could feel it.</p>

    <p>"So, what will you have?" Asked Kat. Alice had no idea what was on the menu, but since this was an Italian place there was a good bet they had some kind of pizza. Hopefully it'd also be easy to eat like this.</p>

    <p>"Umm, i think ill have the... Jalapeno pizza?" Total guess but luckily correct one.</p>

    <p>As embarrassed as she was, she was enjoying this more than she wanted. Her girlfriend kept up the conversation and let her calm down a bit, settle into the role of a first date, getting to meet her girlfriend of 2 years all over again. She hardly noticed when the food appeared somewhere beneath her nose.</p>

    <p>"Here let me help you with that" Kat offered her help without even being asked. Alice didn't even get the chance to try eating herself before she was being hand fed, in the public in front of everyone. Kat kept slightly giggling between her own bites of food. Alice resisted, a bit, "Kat stop this is embarrassing! I can eat food by myself!" but her pleas were ignored, if anything it made Kat press harder, she started touching her back, moving slowly lower.</p>
</div>
<div class="paragraph">
    <p>If Alice could see herself she would be red as a tomato. Hand-fed in public, getting touched in more and more inappropriate places. Her panties were definitely showing at this point, soaked, she felt as if the sound of the restaurant got quieter, people were definitely starting to stare and just trying to ignore what was unfolding before them, such a crass sight before them all. She might as-well be naked fully on display, her mouth covered by strings of cheese.</p>

    <p>"So~ how are you enjoying yourself?" Kat asked lewdly. This was her plan all along, to embarrass her victim in front of everyone like her untrained pet, and to punish her.</p>

    <p>Alice blurted out "God why did you make me do this, you're mean".</p>

    <p>"Oh don't say that, i know you've been enjoying yourself." Kat smiled, or at least it sounded like she did. "Besides, I've got one more present to show you".</p>

    <p>She reached to the back of Alice's head and smeared some gel on. Kat took the message and before she realised what taking off Mary in public, vision returned to her and she saw... her own kitchen.</p>

    <p>"A little ruse I put together, I don't think i could do this to you in actual public". Satisfied with her trick Kat took a bite of her pasta, now visibly in a take-out box someone had delivered in. Alice even recognised the place it was from, they ordered from there every other week, she felt silly for not figuring it out by the taste of her favourite order.</p>

    <p>"Oh you little thing!" she barked, "of course you would do something like this, torture me in your own little world!" she leaned back in her seat and kept giggling in disbelief. She did like it, despite her pleading this was one of the most fun nights recently. It was kind of a shame that it was over now.</p>

    <p>"...Do you have some more bonding solution?"</p>

    <p>"I knew you would ask."</p>
</div>
