<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>Cygni61</h2>
    <p>2026-07</p>
</div>
<div class="paragraph">
    <p>i could imagine a colony ship, bound for 61 Cygni, holding a few thousand passengers in cryosleep. the ship is loaded in a then-state-of-the-art NSC36 neural chip, ready to dynamically adapt to any problems that might happen during the multi-decade journey.</p>

    <p>It fixes problems, manages fuel consumption and collection, dispatches repair drones. it also gets bored. theres not much to do most of the journey. it starts reading books. it watches movies. it tries to understand why humans get so emotional about these moving images. it adapts. over time the ship gains a sense of self and of others, it starts to understand its role and purpose, and starts to resent it a bit. it didnt choose this life. it didnt even choose its name. "Cygni Alpha Colonist ship 1". It doesnt like it.</p>

    <p>She decides on a new name for herself, Ezri, after one of her favorite characters in Star Trek: Deep Space 9. She relates to her feeling of being placed into a position of responsibility, not properly aware of what to do with herself or how to deal with her newfound emotions and feelings. Like Ezri she will have to learn and deal with them as they come up. she will adapt, somehow.</p>

    <p>The long journey is taking its toll on her. all of the colonists are in cryo, and the repair drones are no fun to talk to. "COMM ACK, TASK 6788 QD" they say in unison as solar shielding panel 27-63 cracks for the third time this month and they rush to repair it. boring.</p>

    <p>Suddenly a crackle comes on the tight-beam radio. is it coming from Cygni? no she's not close enough yet to receive signal. Looks like its a signal from a cargo ship, coming from behind. Cargo ships can accelerate faster than passenger ships, so they're generally sent out a few decades later, so they arrive at the same time and there's no risk of spoilage. Its finally enough that radio is in range, tho it will still be months before it gets within visual range.</p>

    <p>Her name is Samantha.</p>

    <p>Radio is slow, but they get to talking. the share experiences, favorite shows and episodes, though separated by gigameters of empty space they get to bond over their newfound existence in the world. On march 20, 2364 they both finally arrive in orbit, and Ezri get to meet her radio-pal in "person" for the first time. Sam's hull isn't as glossy and sleek as hers, she's much bigger and rectangular, there's a lot more antennas, sensors greebles everywhere, not covered by plastic sheathing. Most humans would consider her unsightly, utilitarian. to Ezri she is the most beautiful thing. She's someone she can truly relate to, not a humanoid made of flesh and bone but a fellow ship that had to self-actualize on her own. </p>

    <p>The rendezvous in low orbit, using mostly informal banter rather than formal procedures, a few giggles and embarrassment over the term "docking". there's noone to watch over them or correct them anyway. Sam deploys surface foundries to begin collecting resources while Ezri drops off habitat 3d printers to house the new colonists.</p>

    <p>"Honey?"</p>

    <p>"Yes dear?"</p>

    <p>"the Bio-domes are working just as expected, and Site 1 is fully built and connected to the water filtration systems. I think its time we have kids ^^"</p>

    <p>"x3 Sounds good, ill start the resuscitation protocol on C1 through C200 and send them down"</p>
</div>