
<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>digital</h2>
    <p>2026-09</p>
</div>
<div class="paragraph">
    <p>one of your friends confesses she'd like to be a robot. she has enough money to do the μMRI theseus scan, but not enough for a full robot body. she asks you if she could live on your home network until she makes enough money in her remote programming job to buy it. shouldn't take much now that there's no rent to pay.</p>

    <p>at first she just stays in her little neural core that you picked up at the clinic. she minds her own business, not taking too much internet traffic. she's definitely happier than before, likes to chat about her day with a virtual webcam, changing her avatar over time. she slowly starts daring out to your computer tho, helps out writing code, watches videos with you on friday nights, even makes her own partition on your disk.</p>

    <p>a package shows up in the mail, with a new computer mouse, she says its a present. then a keyboard, new RAM, CPU, more hard drives. she's clearly spending a lot of money, but you don't mind it's free stuff. she moves more and more into your new setup, takes an entire disk for herself, reserves multiple cores.</p>

    <p>one day you come home from work and see the computer is already turned on. on your desktop she shows up with a full avatar, greets you with a warm smile, says she's happy to see you again. she follows your mouse around the desktop, sits on top of your opened windows, smiles at you cutely while kicking her legs in the air. you drag the mouse over her head to pat her and she giggles.</p>

    <p>she quit her job, looks like she's gonna be staying a while. might as well enjoy your new digital pet</p>
</div>