<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>ember</h2>
    <p>2026-02</p>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('ember/ember 16.png') ?>" alt="Ember,a young with short brown air and green, sad dead-looking eyes, frown. she's wearing a plain grey shirt, and a red choker and bow on her head. theres a large scar on her right cheek">
    <h3>Age 16</h3>
    <p>she grew up as a boy on an ice hauler, constantly moving from the asteroid bell to the inner planets, never staying in any one place long enough to call home. as soon as she could she had to help out her parents on the job, except with basically no pay or breaks, regularly verbally abused, sometimes not fed as punishment. what little time she spent in gravity she was sick, her family wasnt willing to buy bone growth treatments calling them a waste of time. because of her weakness she spent most of the time doing chores around the ship; cooking, cleaning, scrubbing gunk off of the carbon filters. </p>

    <p>She randomly found a pen pal, turned friend, when checking wide-beam while passing venus. They got to talking and Ember eventually planned an escape from home. During the next transport she'd hide out in one of the utility containers with a spare O2 tank and spoof the computer to mask her location. It was a risky move, and there was a chance her friend wasn't going to pick her up but she was desperate. After 4 stressful hours in the cold the hatch opened up and she saw March, her friend, and one very pissed but understanding parent.</p>
          
    <p>She worked her ass off to keep her place, luckily her new family was much more inviting and supportive. </p>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('ember/ember 19.png') ?>" alt="Ember. she now has neck-length hair, her eyes are much more vibrant. she's smiling in a hopeful way">
    <h3>Age 19</h3>
    <p>just after she escaped her old home. you can see shes happy about it. the red thing isnt a shirt its a blanket she brought with her, its one of the few things that brought her comfort in her old home. she bought it with the little cash she was able to get, its woven from Devilstrand, a rare fabric made from mycelium, which smells mildly of strawberries. Shes growing her hair out, she's on a centrifugal station so it wont get in the way if its too long. plus it makes her feel much better about herself.</p>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('ember/ember 21.png') ?>" alt="Adult Ember. She dyed her hair bright orange, and has a large white bow on the back of her head. she's wearing a green turtle-neck sleeveless shirt. She has a tattoo on her right shoulder and a trans badge on her chest. her left eye is covered with a medical patch">
    <h3>Age 21</h3>
    <p>She's been finding herself out for the past few months. Bought new clothes, changed her name to Ember. She keeps growing out her hair, now with orange hair dye, it looks nice. </p>
    <p>The eyepatch is from an accident she had a few weeks ago. dumb accident really, a ship leaving from the station started a burn before the clamps disengaged fully. the ship slammed full force to the side and broke open section F. noone was inside luckily, but it jolted the station quite a bit. She was just in the kitchen working with hot oil and it splashed out into her eye.</p>
    <p>The medic told her that she could eventually heal and see out of it normally, but she liked the opportunity to do something cool and decided to get an implant instead</p>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('ember/ember 23.png') ?>" alt="Ember in her weekend outfit. her hair is shoulder-length, along with a green shirt she's wearing a white off-shoulder sweater. her left eye is now gray, with a cross-shaped pupil">
    <p>She worked her ass off to keep her place, luckily her new family was much more inviting and supportive. Eventually she took a culinary course on Venera 7, then an apprenticeship-turned-fulltime job on Venera 5.</p>
    <p>Its simple work in the outpost's canteen but its fulfilling, the people are nice and chatty and she enjoys the peaceful atmosphere. Ironically Venus' atmosphere is incredibly chaotic and hostile on the surface, but shes never been down there and doesnt care. Venus is her favourite planet by far</p>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('ember/ember 26.png') ?>" alt="Ember in her worth clothes. her hair is tied back in a ponytail, she's wearing a green round neck shirt and white apron, and a cook hat. she looks tired but satisfied">
    <p>Ember at her job at the canteen. (pretend shes wearing an apron). she's recently started an online course on baking, she's been trying to make a good tiramisu recipe with cocoa instead of coffee tho shes having some trouble with it getting soggy. She's finally finished moving into her new flat on ring 3, it has a really nice view of the sky but you can still see ring 4 below it, so it doesnt feel too open like you're about to fall down.</p>
    <p>Her roommate is an interesting cookie [ i might talk about her later :3 ], in a lot of ways she's basically the opposite of Ember but she likes spending time with her. its an interesting feeling.</p>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('ember/ember 68.png') ?>" alt="Ember as an old woman. her hair is graying, and back to neck-length, she has smile wrinkles. both her arms are tattooed. she has a satisfied expresion">
    <h3>Age 68</h3>
    <p>shes an old lady now. she was lucky enough to be one of the 25k selected to be aboard the Innes 1, the Proxima Centauri colonization project. She boarded at 42 but even with Its VASIMR engines, the Innes 1 will take over 60 years to reach its destination. Picture is her on her 70th birthday, around the mid-point of their journey. With modern medical advances and de-aging techniques it is very likely she'll live to see the surface of Proxima B, and she is very set on doing so</p>
</div>
<div class="paragraph" style="--accent: var(--color-hl1);">
    <p>I made all these pictures using a <a href="https://picrew.me/en/image_maker/2795963">picrew image maker</a> by the wonderful <a href="https://www.instagram.com/maddel_art/">Maddel</a>. Go check out their art, its great</p>
</div>