<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>style guide</h2>
    <p>i use a specific style when writing, not for any pretentious reasons (i hope) i just like to write like this. thought it would be good to codify it, mostly for my own consistency</p>
</div>
<div class="paragraph">
    <h3>no capitals</h3>
    <p>i don't use capital letters. they always seemed weird, i couldn't quite grasp when to use them and when not to. where i live its basically a complete guess which words in road names are meant to be capitalised. if i didn't have to write emails and snake case code i'd bind my keyboard to not have capitals at all, id fill the keys with diacritics and special characters, but alas.</p>
</div>
<div class="paragraph">
    <h3>space before ! and ?</h3>
    <p>i'm not consistent with this one, it looks slightly better in non-monospace fonts. i thought about adding spaces before . and , too but it made text feel too spaced out. i'm not ruling it out yet tho</p>
</div>
<div class="paragraph">
    <h3>closed compounds</h3>
    <p>this isn't on purpose but i have a lot of word pairs that i leave the space between, at this point i accepted it as just a typing quirk and everyone has to deal with it lol.</p>
    <p>examples include: atleast, atmost
</div>