<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>The art i drew (and dont feel embarrased to put online in my name)</h2>
    <p>I started drawing around the time Sora was announced, i think, at the start of 2024. i didnt do anything creative at the time at all, unless you count programming. i guess you could but it doesnt feel that creative. Anyway i felt really bad and wanted to start drawing so i just... did. took a paper notebook and a pencil and just fukn went for it. im not super consistent with my style or the times i draw, i just make things i want.</p>
    <p>Anyway here's my things. this is <em>not</em> a portfolio, im not an artist. i just draw things, but if you think my stuff is good then im really glad and thank you ^^</p>
    <button id="button-order" type="button">Newest first</button>
    <img id="focused-img"></img>
    <div id="overlay"></div>
</div>
<div class="paragraph">
    <img src="<?= image_url('art/color_9.png') ?>" loading="lazy">
    <img src="<?= image_url('art/color_10.png') ?>" loading="lazy">
    <p>Im really not good at color huh</p>
</div>
<div class="paragraph">
  <img src="<?= image_url('art/pixels_16.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_15.png') ?>" loading="lazy">
  <p>Im trying a thing where i use a small grid with a uniform pixelly brush and just sketch whatever for 20 mins. two of the color ones were alr in this "format" but here's more of them, sketches</p>
  <p>Im calling her hexgirl :&gt;</p>

  <img src="<?= image_url('art/pixels_14.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_13.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_12.png') ?>" loading="lazy">

  <img src="<?= image_url('art/pixels_1.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_11.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_7.png') ?>" loading="lazy">

  <img src="<?= image_url('art/pixels_4.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_5.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_6.png') ?>" loading="lazy">

  <img src="<?= image_url('art/pixels_10.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_8.png') ?>" loading="lazy">
  <img src="<?= image_url('art/pixels_9.png') ?>" loading="lazy">

  <img src="<?= image_url('art/pixels_2.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>Full color!</p>
    <img src="<?= image_url('art/color_1.png') ?>" loading="lazy">
    <img src="<?= image_url('art/color_2.png') ?>" loading="lazy">
    <img src="<?= image_url('art/color_3.png') ?>" loading="lazy">

    <img src="<?= image_url('art/color_4.png') ?>" loading="lazy">
    <img src="<?= image_url('art/color_5.png') ?>" loading="lazy">
    <img src="<?= image_url('art/color_6.png') ?>" loading="lazy">

    <img src="<?= image_url('art/color_7.png') ?>" loading="lazy">
    <img src="<?= image_url('art/color_8.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>Even more sketches</p>
    <img src="<?= image_url('art/sketch3_5.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_9.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_10.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_8.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_20.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch3_1.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_2.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_3.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch3_4.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_6.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_7.png') ?>" loading="lazy">
        
    <img src="<?= image_url('art/sketch3_11.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_12.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_13.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch3_14.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_15.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_16.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch3_17.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_18.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_19.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch3_21.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch3_22.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>Second pfp! The lines in the background are an "interaction net" which is this weird math thingy i was obsessed with, and i still am! its great</p>
    <img src="<?= image_url('art/profile_2.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>More sketches</p>
    <img src="<?= image_url('art/sketch2_1.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_2.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_3.png') ?>" loading="lazy">
        
    <img src="<?= image_url('art/sketch2_4.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_5.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_6.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch2_7.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_8.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_9.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch2_10.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_11.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch2_14.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_15.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch2_16.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_12.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch2_13.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>First pfp i made of myself! I copied the colors from my minecraft skin (i also make minecraft skins!)</p>
    <img src="<?= image_url('art/profile_1.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>I switched to digital! I was "lucky" and my laptop broke and i needed a new one for school, so i bought a cheap tabletPC which came with a stylus. As you can see my art did NOT improve, but it did let me ctrl+z and stuff. i still mostly did random sketches:</p>

    <img src="<?= image_url('art/sketch_1.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_2.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_3.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch_4.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_5.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_6.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch_7.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_8.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_9.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch_10.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_11.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_12.png') ?>" loading="lazy">

    <img src="<?= image_url('art/sketch_13.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_14.png') ?>" loading="lazy">
    <img src="<?= image_url('art/sketch_15.png') ?>" loading="lazy">
</div>
<div class="paragraph">
    <p>This is what i started out with :&gt;</p>
    <p>Literally just paper, pencil and an eraser i found in my drawer (except the eraser, i had to look in an old drawer filled with junk back from middle school!)</p>

    <img src="<?= image_url('art/paper_drawing_1.jpg') ?>" loading="lazy">
    <img src="<?= image_url('art/paper_drawing_4.jpg') ?>" loading="lazy">

    <img src="<?= image_url('art/paper_drawing_6.jpg') ?>" loading="lazy">
    <img src="<?= image_url('art/paper_drawing_7.jpg') ?>" loading="lazy">

    <img src="<?= image_url('art/paper_drawing_2.jpg') ?>" loading="lazy">
    <img src="<?= image_url('art/paper_drawing_3.jpg') ?>" loading="lazy">
    <img src="<?= image_url('art/paper_drawing_5.jpg') ?>" loading="lazy">
</div>
<script src="<?= function_url('gallery.js') ?>"></script>
