<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>hi there!</h2>
    <p>im Erinsc, you can call me Erina, and this is my personal website. I mostly put my art on here, that includes drawings and written short stories, also some topics interesting to me and my recipes. basically anything i wanna share goes up here. </p>
    <p>i'm hosting this whole thing on a raspberry pi 4, so if there's some network issues its probably just raining, give it time.</p>
</div>
<div class="paragraph">
    <h2>main topics</h2>
    <h3><a href=<?= page_url('art')?> >art</a></h3>
    <p>all of the art i made and wanted to share. right now its mostly a documentation of my journey of learning art, its not an intensive thing i just draw what i like and improve slowly.</p>
    <h3><a href=<?= page_url('stories')?>>stories</a></h3>
    <p>i write tiny stories about things i think are interesting, its mostly sci-fi and robot related topics.</p>
    <h3><a href=<?= page_url('recipes')?>>recipes</a></h3>
    <p>i cook ! sometimes. most of these recipes are just slightly adapted from ones i found online or from family, converted to be in grams only (including liquids !), so they're easy to make.</p>
</div>
<div class="paragraph">
    <h3>latest updates</h3>
    <p>2026-08-07 working on version 2 of the website</p>
</div>