<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>recipes that i made / adapted from others</h2>
    <p>fyi i am vegan, so all the recipes here are intended to be too. for example if i say "milk" i mean any kind of, cause they're honesty basically the same (oat milk is goat tho).</p>
    <p>there are ofcourse pictures of all the food, maybe not the most apetizing so be warned, my main priority is that things taste great haha.</p>
</div>
<div class="paragraph">
    <h2>savory</h2>
    <h3><a href=<?= page_url('recipes/lasagna') ?>>lasagna</a></h3>
    <p>a lasagna recipe i've cooked dozens of times, slowly improving each time, it's pretty good.</p>
    <h3><a href=<?= page_url('recipes/macncheese')?>>mac&cheese</a></h3>
    <p>simple mac&cheese recipe with some tofu bacon bits in.</p>
    <h3><a href=<?= page_url('recipes/pizza') ?>>pizza</a></h3>
    <p>TODO</p>
</div>
<div class="paragraph">
    <h2>sweet</h2>
    <h3><a href=<?= page_url('recipes/tiramisu') ?>>tiramisu</a></h3>
    <p>TODO</p>
    <h3><a href=<?= page_url('recipes/carrotcake') ?>>carrot cake</a></h3>
    <p>TODO</p>
    <h3><a href=<?= page_url('recipes/waspnests') ?>>wasps nests</a></h3>
    <p>TODO</p>
    <h3><a href=<?= page_url('recipes/oreoicecream') ?>>oreo ice cream</a></h3>
    <p>TODO</p>
</div>
<div class="paragraph">
    <h2>sauces</h2>
    <h3><a href=<?= page_url('recipes/sweetnsavorysauce') ?>>sweet&savory sauce</a></h3>
    <p>quick dipping sauce for nuggets, potato croquettes and other fried goodies.</p>
</div>