<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>written stories</h2>
    <p>most of these are one-offs that i wrote in one sitting, quality may vary. </p>
</div>
<div class="paragraph">
    <h2>space sci-fi</h2>
    
    <h3><a href=<?= page_url('stories/ember')?> >ember</a></h3>
    <p><s></s>hort journey through the life of a girl in a near space-fairing future.</p>
    <h3><a href=<?= page_url('stories/cygni61')?> >cygni61</a></h3>
    <p>colony ship AI gaining sentience on its decade long journey.</p>
    <h3><a href=<?= page_url('stories/magnetics')?> >magnetics</a></h3>
    <p>zero-mass computing medium concept.</p>
</div>
<div class="paragraph">
    <h2>robots</h2>
    <h3><a href=<?= page_url('stories/mrt')?> >mind replacement therapy</a></h3>
    <p>what if there was hrt for becoming a robot.</p>
    <h3><a href=<?= page_url('stories/digital')?> >digital</a></h3>
    <p>a friend of yours asks to live with you for a bit, luckily she won't take up much space. (this one rocked on tumblr)</p>
    <h3><a href=<?= page_url('stories/meteor_shower')?> >meteor shower</a></h3>
    <p>construction droid waits for the colony ship to arrive to their new home.</p>
</div>
<div class ="paragraph">
    <h3>(offsite) <a href="https://www.tumblr.com/blog/lambdanets">lambda nets</a></h3>
    <p>i write a ton of short posts on my tumblr side-blog, featuring almost always trans robot girls. its not exactly high art but i like it a lot.</p>
</div>