<div class="paragraph" style="--accent: var(--color-hl1);">
    <img class="cover" src="<?= image_url('lasagna/lasagna-3.png') ?>" alt="Glass pot filled with four portions of vegan lasagna, golden-crusted on the sides.">    
    <h2>lasagna</h2>
    <p>probably my favourite recipe that i make, it's fairly complicated, takes atleast 30 minutes to prepare and 60 minutes to cook, so be prepaired, so keep that in mind when trying it for the first time, but it's worth it i promise. </p>
    <p>this isn't based on any single recipe, it's a combination of multiple recipes i've tried over the years and taken the best parts off of. no idea about the nutritional details, just consider this junk food lol.</p>
    <p>make sure you have all the ingredients. this recipe only has one atypical ingredient, nooch, but still do check pls.</p>
</div>
<div class="paragraph">   
    <img class="cover" src="<?= image_url('lasagna/lasagna-1.png') ?>" alt="metal pot filled with tofu noodles, mixed with a marinade, before being cooked." title="pre-cooked tofu with marinade">  
    
    <h3>ingredients</h3>
    <p>the bolognese part:</p>
    <ul>
        <li>15g nooch (nutritional yeast)</li>
        <li>15g soy sauce (dark and light both work)</li>
        <li>20g oil (olive is best)</li>
        <li>10g sugar</li>
        <li>200g tofu</li>
        <li>200g jar of milanese sauce, or other tomato sauce</li>
    </ul> 
    <p>the bechamel sauce:</p>
    <ul>
        <li>45g oil (canola is best)</li>
        <li>50g plain flour</li>
        <li>500g near-boiling water</li>
        <li>vegetable stock for 500g water</li>
        <li>60g milk</li>
        <li>20g butter</li>
        <li>7g nooch</li>
        <li>salt, black pepper</li>
    </ul>
    <p>the rest:</p>
    <ul>
        <li>lasagne pasta, 200g ish, or 4 layers</li>
        <li>shredded cheese (optional)</li>
    </ul>
</div>
<div class="paragraph">
    <img class="cover" src="<?= image_url('lasagna/lasagna-4.png') ?>" alt="Image of a single portion of vegan lasagna, placed on a green plate. the plate is slightly dirty, on account of having been used to eat one portion already." title="mm yum yum very yummy">
    <h3>instructions</h3>
    <ol>
    <li>preheat your oven to 220°C.</li>
    <li>combine the nooch, soy sauce, oil, and sugar into a sauce. you can also add the tofu brine. cut the tofu into noodles or cubes, up to you really, and combine them with the marinade in a pot. bake for 15 minutes, stir lightly, bake for 15 more.</li>
    <li>while the tofu is going, combine the oil and flour in a second pot, stir on mid-to-high heat until the flour very slightly browns. pour in the water (carefully !), then add the vegetable stock, salt and pepper to taste.</li>
    <li>add the milk, butter and nooch into the bechamel. stir everything together and let it reduce on low heat for a while,turn it off if need be.</li>
    <li>when the tofu is done, pour in the jar of tomato sauce and lightly stir to not break the tofu. lower the oven to 180°C.</li>
    <li>start layering the lasagna: small layer of beshamel, pasta, half of the bolognese sauce, pasta, half of beshamel, pasta, rest of bolognese, pasta, rest of beshamel. You can sprinkle some shredded cheese on top but i like it without</li>
    <li>cook in the oven for 60 minutes.</li>
    <li>wait for the lasagna to cool for 5 to 10 minutes, if you cut into it too soon it'll spill slightly. still tastes great but it won't be as pretty.</li>
    </ol>
</div>
<div class="paragraph">
    <h3>caserolle alternative</h3>
    <p>if you dont have lasagna pasta, you can instead make a caserrole using any other pasta, 200g worth. farfalle and fusilli work the best, penne and macaroni will work in a pinch but DO NOT use spaghetti.</p>
    <p>instead of layering the pasta and bechamel, combine the raw pasta with the bolognese sauce, put it all in the pan, and cover with all bechamel. cook time is the same.</p>
</div>