<div class="paragraph" style="--accent: var(--color-hl1);">
    <h2>mac&cheese</h2>
    <p>extremely simple mac&cheese recipe, its nothing glamorous and not meant to be nutritious, just taste good and be filling. i think it does that well.</p>
    <p>takes 40 ish minutes to make, i know that sounds like a lot but most of it you're waiting for the tofu to bake.</p>
    <p>makes 3 ish portions.</p>
</div>
<div class="paragraph">   
    <h3>ingredients</h3>
    <p>the tofu bacon bits:</p>
    <ul>
        <li>15g nooch (nutritional yeast)</li>
        <li>15g soy sauce (dark and light both work)</li>
        <li>20g oil (olive is best)</li>
        <li>10g sugar</li>
        <li>200g tofu</li>
    </ul> 
    <p>the cheese:</p>
    <ul>
        <li>15g oil (canola is best)</li>
        <li>15g plain flour</li>
        <li>TODO g milk</li>
        <li>vegetable stock for 500g water</li>
        <li>TODO g cheese of your choice</li>
        <li>5g nooch</li>
        <li>salt, black pepper</li>
        <li>pinch of turmeric (optional)</li>
    </ul>
    <p>the pasta:</p>
    <ul>
        <li>250g pasta of your choice, ideally one with lots of bends and turns</li>
    </ul>
</div>
<div class="paragraph">
    <h3>instructions</h3>
    <ol>
    <li>preheat your oven to 220°C.</li>
    <li>combine the nooch, soy sauce, oil, and sugar into a sauce. you can also add the tofu brine. cut the tofu into noodles or cubes, up to you really, and combine them with the marinade in a pot. bake for 15 minutes, stir lightly, bake for 15 more.</li>
    <li>while that's going, start boiling some water for the pasta, put the pasta in there.</li>
    <li>combine the oil and flour in a second pot, stir on mid-to-high heat until the flour very slightly browns. pour in the milk, then add the vegetable stock, salt and pepper to taste.</li>
    <li>add the cheese, and optionally turmeric for color, salt, pepper, any other spices you might like. stir everything together and let it reduce on low heat for a while,turn it off if need be.</li>
    <li>when all 3 parts are done, combine them gently together in a pot.</li>
    </ol>
</div>
<div class="paragraph">
    <h3>reheating</h3>
    <p>lots of vegan cheeses tend to firm up a lot when cooled in a fridge, that also makes them lose moisture, so if you can, dont reheat your pasta block in the microwave.</p>
    <p>instead, put a bit of milk into a pot, add the pasta in, and on low heat let it slowly heat through. this can take some time so be patient</p>
</div>